service: tsn-podcast
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${opt:stage, self:provider.stage, 'dev'}}
custom:
  defaultStage: dev
  profiles:
    dev: devProfile
    prod: prodProfile